SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE FROM ANIMAL_INS INS  
          WHERE INS.NAME = 'LUCY' OR INS.NAME = 'ELLA' OR INS.NAME = 'PICKLE'    
          OR INS.NAME = 'ROGAN' OR INS.NAME = 'SABRINA' OR INS.NAME = 'MITTY' 
          ORDER BY INS.ANIMAL_ID ASC
