SELECT YEAR(OS.SALES_DATE) AS YEAR, 
       MONTH(OS.SALES_DATE) AS MONTH ,
       count(DISTINCT OS.USER_ID) AS PURCHASED_USERS , 
       ROUND(COUNT(DISTINCT OS.USER_ID)/CNT,1) AS PUCHASED_RATIO
FROM USER_INFO UI 
INNER JOIN ONLINE_SALE OS
ON UI.USER_ID = OS.USER_ID 
INNER JOIN (SELECT COUNT(1) AS cnt FROM USER_INFO WHERE YEAR(JOINED)='2021') UI2
WHERE YEAR(UI.JOINED) = '2021'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH